### ISSUE TITLE
Homebase bugs

### ISSUE THREAD

**Issue by imtds-devel** [ffroggy/sidekick#13]
Lots of bugs to fix here!

* Events/Announcements all post as nchera13
* Random /p> shows up at end of text
* Create announcement/event: currently selected type of post should be indicated by the status bar in the modal
* Labels for announcement/event are cut off by text box on Safari
* Swap subject and announcement in create announcement (subject implies title, announcement implies text)
* Character limit on subject (for display purposes)
* Edit/delete announcements
* For events: time instead of end date
* Sizing of homing beacon images is off on really wide screens
* Checkin button is broken

**Comment by ffroggy** [comment]
Events/Announcements now seem to be posting properly

**Comment by ffroggy** [comment]
random /p> is fixed too

**Comment by ffroggy** [comment]
Completely redid the Event and Announcement adding modal so that it no longer relies on ModelForms!

**Comment by ffroggy** [comment]
Checkin button is now functional and the headers display properly

**Comment by ffroggy** [comment]
Ok, added smaller buttons for checkin (better for mobile), updated version num, and added an additional link for the papercut admin! With that, we're good to go so I'm gonna close out this feature!
